version: '3.7'
# config com base em
# https://imasters.com.br/php/criando-um-ambiente-de-desenvolvimento-php-minimo-com-docker-p3
services:
  nginx:
    image: nginx:1.17.3
    container_name: nginx
    networks:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/html/"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php
      - mysql
  php:
    build: ./
    networks:
      - backend
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    environment:
      - ENVIRONMENT=development
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - backend
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'petry'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '123456'
networks:
  backend:
volumes:
  mysql: